/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboardStats {
  'totalTests' : bigint,
  'totalActiveUsers' : bigint,
  'topTests' : Array<TopTestInfo>,
  'totalQuestions' : bigint,
  'totalDeactivatedUsers' : bigint,
  'totalMasteredQuestions' : bigint,
  'totalMasteryRecords' : bigint,
  'totalUsers' : bigint,
}
export interface AdminUserInfo {
  'username' : UserId,
  'displayName' : string,
  'role' : { 'admin' : null } |
    { 'user' : null },
  'isActive' : boolean,
}
export interface AllTestData {
  'tests' : Array<TestFullData>,
  'manifest' : DataManifest,
}
export interface AnswerSubmission {
  'selectedOptions' : Array<bigint>,
  'orderedItems' : Array<bigint>,
  'textAnswer' : string,
  'questionId' : bigint,
}
export interface CreateQuestionInput {
  'imageBlob' : [] | [ExternalBlob],
  'explanation' : [] | [string],
  'text' : string,
  'audioUrl' : [] | [string],
  'questionType' : QuestionType,
  'sectionId' : [] | [bigint],
  'correctAnswers' : Array<bigint>,
  'correctText' : string,
  'correctOrder' : Array<bigint>,
  'options' : Array<string>,
}
export interface CreateSectionInput { 'name' : string, 'description' : string }
export interface CreateTestInput { 'name' : string, 'description' : string }
export interface DataManifest {
  'testCount' : bigint,
  'globalUpdatedAt' : string,
  'sectionCount' : bigint,
  'checksum' : string,
  'questionCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export type LoginResult = { 'ok' : UserSession } |
  { 'err' : string } |
  { 'accountDeactivated' : null } |
  { 'requiresTOTP' : null };
export interface Question {
  'id' : bigint,
  'imageBlob' : [] | [ExternalBlob],
  'explanation' : [] | [string],
  'questionUpdatedAt' : bigint,
  'text' : string,
  'audioUrl' : [] | [string],
  'questionType' : QuestionType,
  'sectionId' : [] | [bigint],
  'correctAnswers' : Array<bigint>,
  'correctText' : string,
  'correctOrder' : Array<bigint>,
  'testId' : bigint,
  'options' : Array<string>,
  'orderIndex' : bigint,
}
export type QuestionId = bigint;
export interface QuestionMastery {
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'isMastered' : boolean,
  'questionId' : QuestionId,
  'testId' : TestId,
  'correctStreak' : bigint,
}
export interface QuestionResult { 'isCorrect' : boolean, 'questionId' : bigint }
export type QuestionType = { 'textInput' : null } |
  { 'mcSingle' : null } |
  { 'dragOrder' : null } |
  { 'mcMulti' : null };
export interface ResetMasteryInput {
  'sectionId' : [] | [SectionId],
  'testId' : TestId,
}
export interface ReviewData {
  'totalScore' : number,
  'questions' : Array<ReviewQuestion>,
  'sectionScores' : Array<SectionResult>,
}
export interface ReviewQuestion {
  'question' : {
    'id' : bigint,
    'explanation' : [] | [string],
    'text' : string,
    'questionType' : { 'textInput' : null } |
      { 'mcSingle' : null } |
      { 'dragOrder' : null } |
      { 'mcMulti' : null },
    'options' : Array<string>,
  },
  'correctAnswer' : string,
  'userAnswer' : string,
  'isCorrect' : boolean,
}
export interface Section {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'testId' : bigint,
}
export interface SectionData {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'testId' : bigint,
}
export type SectionId = bigint;
export interface SectionMasteryInfo {
  'timeSpentSeconds' : bigint,
  'totalInSection' : bigint,
  'sectionName' : string,
  'sectionId' : SectionId,
  'masteredCount' : bigint,
  'isSectionMastered' : boolean,
}
export interface SectionResult {
  'sectionName' : string,
  'score' : bigint,
  'sectionId' : bigint,
  'totalQuestions' : bigint,
}
export interface SessionInfo {
  'completed' : boolean,
  'sessionId' : string,
  'testId' : bigint,
}
export interface Test {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface TestFullData {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'questions' : Array<Question>,
  'sections' : Array<SectionData>,
}
export type TestId = bigint;
export interface TestMasteryInfo {
  'timeSpentSeconds' : bigint,
  'inProgressCount' : bigint,
  'testName' : string,
  'totalQuestions' : bigint,
  'isTestMastered' : boolean,
  'masteredCount' : bigint,
  'sections' : Array<SectionMasteryInfo>,
  'testId' : TestId,
}
export interface TestProgress {
  'username' : string,
  'answers' : Array<AnswerSubmission>,
  'selectedSectionIds' : Array<bigint>,
  'savedAt' : bigint,
  'sessionId' : string,
  'testId' : bigint,
}
export interface TestResult {
  'completedAt' : bigint,
  'timeSpentSeconds' : bigint,
  'username' : string,
  'questionResults' : Array<QuestionResult>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'sessionId' : string,
  'testId' : bigint,
  'sectionResults' : Array<SectionResult>,
}
export type Timestamp = bigint;
export interface TopTestInfo {
  'testName' : string,
  'testId' : TestId,
  'sessionCount' : bigint,
}
export interface UpdateQuestionInput {
  'imageBlob' : [] | [ExternalBlob],
  'explanation' : [] | [string],
  'text' : string,
  'audioUrl' : [] | [string],
  'questionType' : QuestionType,
  'sectionId' : [] | [bigint],
  'correctAnswers' : Array<bigint>,
  'correctText' : string,
  'correctOrder' : Array<bigint>,
  'options' : Array<string>,
}
export interface UpdateSectionInput { 'name' : string, 'description' : string }
export interface UpdateTestInput { 'name' : string, 'description' : string }
export interface UserDetailedProgress {
  'tests' : Array<TestMasteryInfo>,
  'username' : UserId,
  'lifetimeTimeSpentSeconds' : bigint,
}
export type UserId = string;
export interface UserProgressInfo {
  'inProgressCount' : bigint,
  'username' : UserId,
  'totalQuestions' : bigint,
  'masteredCount' : bigint,
  'testId' : TestId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export interface UserSession {
  'username' : string,
  'displayName' : [] | [string],
  'role' : UserRole,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addQuestion' : ActorMethod<[string, bigint, CreateQuestionInput], Question>,
  'adminActivateUser' : ActorMethod<[string, UserId], boolean>,
  'adminDeactivateUser' : ActorMethod<[string, UserId], boolean>,
  'adminDeleteUser' : ActorMethod<
    [string, UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetUserDetailedProgress' : ActorMethod<
    [string, UserId],
    UserDetailedProgress
  >,
  'adminGetUserProgress' : ActorMethod<
    [string, UserId, TestId],
    [] | [UserProgressInfo]
  >,
  'adminListUsers' : ActorMethod<[string], Array<AdminUserInfo>>,
  'adminResetUserMastery' : ActorMethod<
    [string, UserId, ResetMasteryInput],
    boolean
  >,
  'createSection' : ActorMethod<[string, bigint, CreateSectionInput], Section>,
  'createTest' : ActorMethod<[string, CreateTestInput], Test>,
  'deleteQuestion' : ActorMethod<[string, bigint], boolean>,
  'deleteSection' : ActorMethod<[string, bigint], boolean>,
  'deleteTest' : ActorMethod<[string, bigint], boolean>,
  'disable2FA' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'enable2FA' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAdminDashboardStats' : ActorMethod<[string], AdminDashboardStats>,
  'getAllTestData' : ActorMethod<[], AllTestData>,
  'getDataManifest' : ActorMethod<[], DataManifest>,
  'getMasteryForTest' : ActorMethod<[string, TestId], Array<QuestionMastery>>,
  'getQuestion' : ActorMethod<[bigint], [] | [Question]>,
  'getSection' : ActorMethod<[bigint], [] | [Section]>,
  'getTest' : ActorMethod<[bigint], [] | [Test]>,
  'getTestProgress' : ActorMethod<
    [string, bigint, string],
    [] | [TestProgress]
  >,
  'getTestResult' : ActorMethod<[string, bigint], [] | [TestResult]>,
  'getTestResultBySession' : ActorMethod<
    [string, bigint, string],
    [] | [TestResult]
  >,
  'getTestReview' : ActorMethod<[string, bigint, string], [] | [ReviewData]>,
  'getTwoFAStatus' : ActorMethod<[string], boolean>,
  'getUserProgress' : ActorMethod<[UserId], UserDetailedProgress>,
  'getUserRole' : ActorMethod<[string], [] | [UserRole]>,
  'listActiveTestSessions' : ActorMethod<[string], Array<SessionInfo>>,
  'listMyTestResults' : ActorMethod<[string], Array<TestResult>>,
  'listQuestionsForTest' : ActorMethod<[bigint], Array<Question>>,
  'listSectionsForTest' : ActorMethod<[bigint], Array<Section>>,
  'listTests' : ActorMethod<[], Array<Test>>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'register' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetMyMastery' : ActorMethod<[string, ResetMasteryInput], undefined>,
  'saveTestProgress' : ActorMethod<
    [string, bigint, string, Array<AnswerSubmission>],
    undefined
  >,
  'setup2FA' : ActorMethod<
    [string],
    { 'ok' : [string, string] } |
      { 'err' : string }
  >,
  'submitTestAnswers' : ActorMethod<
    [string, bigint, string, Array<AnswerSubmission>, bigint],
    TestResult
  >,
  'updatePassword' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateQuestion' : ActorMethod<
    [string, bigint, UpdateQuestionInput],
    [] | [Question]
  >,
  'updateSection' : ActorMethod<
    [string, bigint, UpdateSectionInput],
    [] | [Section]
  >,
  'updateTest' : ActorMethod<[string, bigint, UpdateTestInput], [] | [Test]>,
  'verifyTOTPLogin' : ActorMethod<
    [string, string],
    { 'ok' : UserSession } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];