/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const QuestionType = IDL.Variant({
  'textInput' : IDL.Null,
  'mcSingle' : IDL.Null,
  'dragOrder' : IDL.Null,
  'mcMulti' : IDL.Null,
});
export const CreateQuestionInput = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'explanation' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
  'questionType' : QuestionType,
  'sectionId' : IDL.Opt(IDL.Nat),
  'correctAnswers' : IDL.Vec(IDL.Nat),
  'correctText' : IDL.Text,
  'correctOrder' : IDL.Vec(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'explanation' : IDL.Opt(IDL.Text),
  'questionUpdatedAt' : IDL.Int,
  'text' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
  'questionType' : QuestionType,
  'sectionId' : IDL.Opt(IDL.Nat),
  'correctAnswers' : IDL.Vec(IDL.Nat),
  'correctText' : IDL.Text,
  'correctOrder' : IDL.Vec(IDL.Nat),
  'testId' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
  'orderIndex' : IDL.Nat,
});
export const UserId = IDL.Text;
export const SectionId = IDL.Nat;
export const SectionMasteryInfo = IDL.Record({
  'timeSpentSeconds' : IDL.Nat,
  'totalInSection' : IDL.Nat,
  'sectionName' : IDL.Text,
  'sectionId' : SectionId,
  'masteredCount' : IDL.Nat,
  'isSectionMastered' : IDL.Bool,
});
export const TestId = IDL.Nat;
export const TestMasteryInfo = IDL.Record({
  'timeSpentSeconds' : IDL.Nat,
  'inProgressCount' : IDL.Nat,
  'testName' : IDL.Text,
  'totalQuestions' : IDL.Nat,
  'isTestMastered' : IDL.Bool,
  'masteredCount' : IDL.Nat,
  'sections' : IDL.Vec(SectionMasteryInfo),
  'testId' : TestId,
});
export const UserDetailedProgress = IDL.Record({
  'tests' : IDL.Vec(TestMasteryInfo),
  'username' : UserId,
  'lifetimeTimeSpentSeconds' : IDL.Nat,
});
export const UserProgressInfo = IDL.Record({
  'inProgressCount' : IDL.Nat,
  'username' : UserId,
  'totalQuestions' : IDL.Nat,
  'masteredCount' : IDL.Nat,
  'testId' : TestId,
});
export const AdminUserInfo = IDL.Record({
  'username' : UserId,
  'displayName' : IDL.Text,
  'role' : IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null }),
  'isActive' : IDL.Bool,
});
export const ResetMasteryInput = IDL.Record({
  'sectionId' : IDL.Opt(SectionId),
  'testId' : TestId,
});
export const CreateSectionInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Section = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'testId' : IDL.Nat,
});
export const CreateTestInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const TopTestInfo = IDL.Record({
  'testName' : IDL.Text,
  'testId' : TestId,
  'sessionCount' : IDL.Nat,
});
export const AdminDashboardStats = IDL.Record({
  'totalTests' : IDL.Nat,
  'totalActiveUsers' : IDL.Nat,
  'topTests' : IDL.Vec(TopTestInfo),
  'totalQuestions' : IDL.Nat,
  'totalDeactivatedUsers' : IDL.Nat,
  'totalMasteredQuestions' : IDL.Nat,
  'totalMasteryRecords' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const SectionData = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'testId' : IDL.Nat,
});
export const TestFullData = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'questions' : IDL.Vec(Question),
  'sections' : IDL.Vec(SectionData),
});
export const DataManifest = IDL.Record({
  'testCount' : IDL.Nat,
  'globalUpdatedAt' : IDL.Text,
  'sectionCount' : IDL.Nat,
  'checksum' : IDL.Text,
  'questionCount' : IDL.Nat,
});
export const AllTestData = IDL.Record({
  'tests' : IDL.Vec(TestFullData),
  'manifest' : DataManifest,
});
export const Timestamp = IDL.Int;
export const QuestionId = IDL.Nat;
export const QuestionMastery = IDL.Record({
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'isMastered' : IDL.Bool,
  'questionId' : QuestionId,
  'testId' : TestId,
  'correctStreak' : IDL.Nat,
});
export const AnswerSubmission = IDL.Record({
  'selectedOptions' : IDL.Vec(IDL.Nat),
  'orderedItems' : IDL.Vec(IDL.Nat),
  'textAnswer' : IDL.Text,
  'questionId' : IDL.Nat,
});
export const TestProgress = IDL.Record({
  'username' : IDL.Text,
  'answers' : IDL.Vec(AnswerSubmission),
  'selectedSectionIds' : IDL.Vec(IDL.Nat),
  'savedAt' : IDL.Int,
  'sessionId' : IDL.Text,
  'testId' : IDL.Nat,
});
export const QuestionResult = IDL.Record({
  'isCorrect' : IDL.Bool,
  'questionId' : IDL.Nat,
});
export const SectionResult = IDL.Record({
  'sectionName' : IDL.Text,
  'score' : IDL.Nat,
  'sectionId' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
});
export const TestResult = IDL.Record({
  'completedAt' : IDL.Int,
  'timeSpentSeconds' : IDL.Nat,
  'username' : IDL.Text,
  'questionResults' : IDL.Vec(QuestionResult),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'sessionId' : IDL.Text,
  'testId' : IDL.Nat,
  'sectionResults' : IDL.Vec(SectionResult),
});
export const ReviewQuestion = IDL.Record({
  'question' : IDL.Record({
    'id' : IDL.Nat,
    'explanation' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'questionType' : IDL.Variant({
      'textInput' : IDL.Null,
      'mcSingle' : IDL.Null,
      'dragOrder' : IDL.Null,
      'mcMulti' : IDL.Null,
    }),
    'options' : IDL.Vec(IDL.Text),
  }),
  'correctAnswer' : IDL.Text,
  'userAnswer' : IDL.Text,
  'isCorrect' : IDL.Bool,
});
export const ReviewData = IDL.Record({
  'totalScore' : IDL.Float64,
  'questions' : IDL.Vec(ReviewQuestion),
  'sectionScores' : IDL.Vec(SectionResult),
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const SessionInfo = IDL.Record({
  'completed' : IDL.Bool,
  'sessionId' : IDL.Text,
  'testId' : IDL.Nat,
});
export const UserSession = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Opt(IDL.Text),
  'role' : UserRole,
});
export const LoginResult = IDL.Variant({
  'ok' : UserSession,
  'err' : IDL.Text,
  'accountDeactivated' : IDL.Null,
  'requiresTOTP' : IDL.Null,
});
export const UpdateQuestionInput = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'explanation' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
  'questionType' : QuestionType,
  'sectionId' : IDL.Opt(IDL.Nat),
  'correctAnswers' : IDL.Vec(IDL.Nat),
  'correctText' : IDL.Text,
  'correctOrder' : IDL.Vec(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
});
export const UpdateSectionInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UpdateTestInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Nat, CreateQuestionInput],
      [Question],
      [],
    ),
  'adminActivateUser' : IDL.Func([IDL.Text, UserId], [IDL.Bool], []),
  'adminDeactivateUser' : IDL.Func([IDL.Text, UserId], [IDL.Bool], []),
  'adminDeleteUser' : IDL.Func(
      [IDL.Text, UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetUserDetailedProgress' : IDL.Func(
      [IDL.Text, UserId],
      [UserDetailedProgress],
      ['query'],
    ),
  'adminGetUserProgress' : IDL.Func(
      [IDL.Text, UserId, TestId],
      [IDL.Opt(UserProgressInfo)],
      ['query'],
    ),
  'adminListUsers' : IDL.Func([IDL.Text], [IDL.Vec(AdminUserInfo)], ['query']),
  'adminResetUserMastery' : IDL.Func(
      [IDL.Text, UserId, ResetMasteryInput],
      [IDL.Bool],
      [],
    ),
  'createSection' : IDL.Func(
      [IDL.Text, IDL.Nat, CreateSectionInput],
      [Section],
      [],
    ),
  'createTest' : IDL.Func([IDL.Text, CreateTestInput], [Test], []),
  'deleteQuestion' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteSection' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'disable2FA' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'enable2FA' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAdminDashboardStats' : IDL.Func(
      [IDL.Text],
      [AdminDashboardStats],
      ['query'],
    ),
  'getAllTestData' : IDL.Func([], [AllTestData], ['query']),
  'getDataManifest' : IDL.Func([], [DataManifest], ['query']),
  'getMasteryForTest' : IDL.Func(
      [IDL.Text, TestId],
      [IDL.Vec(QuestionMastery)],
      ['query'],
    ),
  'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
  'getSection' : IDL.Func([IDL.Nat], [IDL.Opt(Section)], ['query']),
  'getTest' : IDL.Func([IDL.Nat], [IDL.Opt(Test)], ['query']),
  'getTestProgress' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(TestProgress)],
      ['query'],
    ),
  'getTestResult' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(TestResult)],
      ['query'],
    ),
  'getTestResultBySession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(TestResult)],
      ['query'],
    ),
  'getTestReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(ReviewData)],
      ['query'],
    ),
  'getTwoFAStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getUserProgress' : IDL.Func([UserId], [UserDetailedProgress], ['query']),
  'getUserRole' : IDL.Func([IDL.Text], [IDL.Opt(UserRole)], ['query']),
  'listActiveTestSessions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SessionInfo)],
      ['query'],
    ),
  'listMyTestResults' : IDL.Func([IDL.Text], [IDL.Vec(TestResult)], ['query']),
  'listQuestionsForTest' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'listSectionsForTest' : IDL.Func([IDL.Nat], [IDL.Vec(Section)], ['query']),
  'listTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetMyMastery' : IDL.Func([IDL.Text, ResetMasteryInput], [], []),
  'saveTestProgress' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(AnswerSubmission)],
      [],
      [],
    ),
  'setup2FA' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Tuple(IDL.Text, IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'submitTestAnswers' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(AnswerSubmission), IDL.Nat],
      [TestResult],
      [],
    ),
  'updatePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateQuestion' : IDL.Func(
      [IDL.Text, IDL.Nat, UpdateQuestionInput],
      [IDL.Opt(Question)],
      [],
    ),
  'updateSection' : IDL.Func(
      [IDL.Text, IDL.Nat, UpdateSectionInput],
      [IDL.Opt(Section)],
      [],
    ),
  'updateTest' : IDL.Func(
      [IDL.Text, IDL.Nat, UpdateTestInput],
      [IDL.Opt(Test)],
      [],
    ),
  'verifyTOTPLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserSession, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const QuestionType = IDL.Variant({
    'textInput' : IDL.Null,
    'mcSingle' : IDL.Null,
    'dragOrder' : IDL.Null,
    'mcMulti' : IDL.Null,
  });
  const CreateQuestionInput = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'explanation' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
    'questionType' : QuestionType,
    'sectionId' : IDL.Opt(IDL.Nat),
    'correctAnswers' : IDL.Vec(IDL.Nat),
    'correctText' : IDL.Text,
    'correctOrder' : IDL.Vec(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'explanation' : IDL.Opt(IDL.Text),
    'questionUpdatedAt' : IDL.Int,
    'text' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
    'questionType' : QuestionType,
    'sectionId' : IDL.Opt(IDL.Nat),
    'correctAnswers' : IDL.Vec(IDL.Nat),
    'correctText' : IDL.Text,
    'correctOrder' : IDL.Vec(IDL.Nat),
    'testId' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
    'orderIndex' : IDL.Nat,
  });
  const UserId = IDL.Text;
  const SectionId = IDL.Nat;
  const SectionMasteryInfo = IDL.Record({
    'timeSpentSeconds' : IDL.Nat,
    'totalInSection' : IDL.Nat,
    'sectionName' : IDL.Text,
    'sectionId' : SectionId,
    'masteredCount' : IDL.Nat,
    'isSectionMastered' : IDL.Bool,
  });
  const TestId = IDL.Nat;
  const TestMasteryInfo = IDL.Record({
    'timeSpentSeconds' : IDL.Nat,
    'inProgressCount' : IDL.Nat,
    'testName' : IDL.Text,
    'totalQuestions' : IDL.Nat,
    'isTestMastered' : IDL.Bool,
    'masteredCount' : IDL.Nat,
    'sections' : IDL.Vec(SectionMasteryInfo),
    'testId' : TestId,
  });
  const UserDetailedProgress = IDL.Record({
    'tests' : IDL.Vec(TestMasteryInfo),
    'username' : UserId,
    'lifetimeTimeSpentSeconds' : IDL.Nat,
  });
  const UserProgressInfo = IDL.Record({
    'inProgressCount' : IDL.Nat,
    'username' : UserId,
    'totalQuestions' : IDL.Nat,
    'masteredCount' : IDL.Nat,
    'testId' : TestId,
  });
  const AdminUserInfo = IDL.Record({
    'username' : UserId,
    'displayName' : IDL.Text,
    'role' : IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null }),
    'isActive' : IDL.Bool,
  });
  const ResetMasteryInput = IDL.Record({
    'sectionId' : IDL.Opt(SectionId),
    'testId' : TestId,
  });
  const CreateSectionInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Section = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'testId' : IDL.Nat,
  });
  const CreateTestInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const TopTestInfo = IDL.Record({
    'testName' : IDL.Text,
    'testId' : TestId,
    'sessionCount' : IDL.Nat,
  });
  const AdminDashboardStats = IDL.Record({
    'totalTests' : IDL.Nat,
    'totalActiveUsers' : IDL.Nat,
    'topTests' : IDL.Vec(TopTestInfo),
    'totalQuestions' : IDL.Nat,
    'totalDeactivatedUsers' : IDL.Nat,
    'totalMasteredQuestions' : IDL.Nat,
    'totalMasteryRecords' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const SectionData = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'testId' : IDL.Nat,
  });
  const TestFullData = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'questions' : IDL.Vec(Question),
    'sections' : IDL.Vec(SectionData),
  });
  const DataManifest = IDL.Record({
    'testCount' : IDL.Nat,
    'globalUpdatedAt' : IDL.Text,
    'sectionCount' : IDL.Nat,
    'checksum' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  const AllTestData = IDL.Record({
    'tests' : IDL.Vec(TestFullData),
    'manifest' : DataManifest,
  });
  const Timestamp = IDL.Int;
  const QuestionId = IDL.Nat;
  const QuestionMastery = IDL.Record({
    'userId' : UserId,
    'updatedAt' : Timestamp,
    'isMastered' : IDL.Bool,
    'questionId' : QuestionId,
    'testId' : TestId,
    'correctStreak' : IDL.Nat,
  });
  const AnswerSubmission = IDL.Record({
    'selectedOptions' : IDL.Vec(IDL.Nat),
    'orderedItems' : IDL.Vec(IDL.Nat),
    'textAnswer' : IDL.Text,
    'questionId' : IDL.Nat,
  });
  const TestProgress = IDL.Record({
    'username' : IDL.Text,
    'answers' : IDL.Vec(AnswerSubmission),
    'selectedSectionIds' : IDL.Vec(IDL.Nat),
    'savedAt' : IDL.Int,
    'sessionId' : IDL.Text,
    'testId' : IDL.Nat,
  });
  const QuestionResult = IDL.Record({
    'isCorrect' : IDL.Bool,
    'questionId' : IDL.Nat,
  });
  const SectionResult = IDL.Record({
    'sectionName' : IDL.Text,
    'score' : IDL.Nat,
    'sectionId' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
  });
  const TestResult = IDL.Record({
    'completedAt' : IDL.Int,
    'timeSpentSeconds' : IDL.Nat,
    'username' : IDL.Text,
    'questionResults' : IDL.Vec(QuestionResult),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'sessionId' : IDL.Text,
    'testId' : IDL.Nat,
    'sectionResults' : IDL.Vec(SectionResult),
  });
  const ReviewQuestion = IDL.Record({
    'question' : IDL.Record({
      'id' : IDL.Nat,
      'explanation' : IDL.Opt(IDL.Text),
      'text' : IDL.Text,
      'questionType' : IDL.Variant({
        'textInput' : IDL.Null,
        'mcSingle' : IDL.Null,
        'dragOrder' : IDL.Null,
        'mcMulti' : IDL.Null,
      }),
      'options' : IDL.Vec(IDL.Text),
    }),
    'correctAnswer' : IDL.Text,
    'userAnswer' : IDL.Text,
    'isCorrect' : IDL.Bool,
  });
  const ReviewData = IDL.Record({
    'totalScore' : IDL.Float64,
    'questions' : IDL.Vec(ReviewQuestion),
    'sectionScores' : IDL.Vec(SectionResult),
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const SessionInfo = IDL.Record({
    'completed' : IDL.Bool,
    'sessionId' : IDL.Text,
    'testId' : IDL.Nat,
  });
  const UserSession = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Opt(IDL.Text),
    'role' : UserRole,
  });
  const LoginResult = IDL.Variant({
    'ok' : UserSession,
    'err' : IDL.Text,
    'accountDeactivated' : IDL.Null,
    'requiresTOTP' : IDL.Null,
  });
  const UpdateQuestionInput = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'explanation' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
    'questionType' : QuestionType,
    'sectionId' : IDL.Opt(IDL.Nat),
    'correctAnswers' : IDL.Vec(IDL.Nat),
    'correctText' : IDL.Text,
    'correctOrder' : IDL.Vec(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
  });
  const UpdateSectionInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UpdateTestInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Nat, CreateQuestionInput],
        [Question],
        [],
      ),
    'adminActivateUser' : IDL.Func([IDL.Text, UserId], [IDL.Bool], []),
    'adminDeactivateUser' : IDL.Func([IDL.Text, UserId], [IDL.Bool], []),
    'adminDeleteUser' : IDL.Func(
        [IDL.Text, UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetUserDetailedProgress' : IDL.Func(
        [IDL.Text, UserId],
        [UserDetailedProgress],
        ['query'],
      ),
    'adminGetUserProgress' : IDL.Func(
        [IDL.Text, UserId, TestId],
        [IDL.Opt(UserProgressInfo)],
        ['query'],
      ),
    'adminListUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdminUserInfo)],
        ['query'],
      ),
    'adminResetUserMastery' : IDL.Func(
        [IDL.Text, UserId, ResetMasteryInput],
        [IDL.Bool],
        [],
      ),
    'createSection' : IDL.Func(
        [IDL.Text, IDL.Nat, CreateSectionInput],
        [Section],
        [],
      ),
    'createTest' : IDL.Func([IDL.Text, CreateTestInput], [Test], []),
    'deleteQuestion' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteSection' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteTest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'disable2FA' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'enable2FA' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAdminDashboardStats' : IDL.Func(
        [IDL.Text],
        [AdminDashboardStats],
        ['query'],
      ),
    'getAllTestData' : IDL.Func([], [AllTestData], ['query']),
    'getDataManifest' : IDL.Func([], [DataManifest], ['query']),
    'getMasteryForTest' : IDL.Func(
        [IDL.Text, TestId],
        [IDL.Vec(QuestionMastery)],
        ['query'],
      ),
    'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
    'getSection' : IDL.Func([IDL.Nat], [IDL.Opt(Section)], ['query']),
    'getTest' : IDL.Func([IDL.Nat], [IDL.Opt(Test)], ['query']),
    'getTestProgress' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(TestProgress)],
        ['query'],
      ),
    'getTestResult' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(TestResult)],
        ['query'],
      ),
    'getTestResultBySession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(TestResult)],
        ['query'],
      ),
    'getTestReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(ReviewData)],
        ['query'],
      ),
    'getTwoFAStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getUserProgress' : IDL.Func([UserId], [UserDetailedProgress], ['query']),
    'getUserRole' : IDL.Func([IDL.Text], [IDL.Opt(UserRole)], ['query']),
    'listActiveTestSessions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SessionInfo)],
        ['query'],
      ),
    'listMyTestResults' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TestResult)],
        ['query'],
      ),
    'listQuestionsForTest' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'listSectionsForTest' : IDL.Func([IDL.Nat], [IDL.Vec(Section)], ['query']),
    'listTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetMyMastery' : IDL.Func([IDL.Text, ResetMasteryInput], [], []),
    'saveTestProgress' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(AnswerSubmission)],
        [],
        [],
      ),
    'setup2FA' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Tuple(IDL.Text, IDL.Text),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'submitTestAnswers' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(AnswerSubmission), IDL.Nat],
        [TestResult],
        [],
      ),
    'updatePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateQuestion' : IDL.Func(
        [IDL.Text, IDL.Nat, UpdateQuestionInput],
        [IDL.Opt(Question)],
        [],
      ),
    'updateSection' : IDL.Func(
        [IDL.Text, IDL.Nat, UpdateSectionInput],
        [IDL.Opt(Section)],
        [],
      ),
    'updateTest' : IDL.Func(
        [IDL.Text, IDL.Nat, UpdateTestInput],
        [IDL.Opt(Test)],
        [],
      ),
    'verifyTOTPLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserSession, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };