/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TestProgress {
    username: string;
    answers: Array<AnswerSubmission>;
    selectedSectionIds: Array<bigint>;
    savedAt: bigint;
    sessionId: string;
    testId: bigint;
}
export type Timestamp = bigint;
export interface UserSession {
    username: string;
    displayName?: string;
    role: UserRole;
}
export interface AllTestData {
    tests: Array<TestFullData>;
    manifest: DataManifest;
}
export interface AdminDashboardStats {
    totalTests: bigint;
    totalActiveUsers: bigint;
    topTests: Array<TopTestInfo>;
    totalQuestions: bigint;
    totalDeactivatedUsers: bigint;
    totalMasteredQuestions: bigint;
    totalMasteryRecords: bigint;
    totalUsers: bigint;
}
export interface CreateSectionInput {
    name: string;
    description: string;
}
export interface TestMasteryInfo {
    timeSpentSeconds: bigint;
    inProgressCount: bigint;
    testName: string;
    totalQuestions: bigint;
    isTestMastered: boolean;
    masteredCount: bigint;
    sections: Array<SectionMasteryInfo>;
    testId: TestId;
}
export interface SectionResult {
    sectionName: string;
    score: bigint;
    sectionId: bigint;
    totalQuestions: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CreateQuestionInput {
    imageBlob?: ExternalBlob;
    explanation?: string;
    text: string;
    audioUrl?: string;
    questionType: QuestionType;
    sectionId?: bigint;
    correctAnswers: Array<bigint>;
    correctText: string;
    correctOrder: Array<bigint>;
    options: Array<string>;
}
export interface SessionInfo {
    completed: boolean;
    sessionId: string;
    testId: bigint;
}
export interface TopTestInfo {
    testName: string;
    testId: TestId;
    sessionCount: bigint;
}
export interface ReviewQuestion {
    question: {
        id: bigint;
        explanation?: string;
        text: string;
        questionType: QuestionType;
        options: Array<string>;
    };
    correctAnswer: string;
    userAnswer: string;
    isCorrect: boolean;
}
export interface CreateTestInput {
    name: string;
    description: string;
}
export interface UpdateSectionInput {
    name: string;
    description: string;
}
export interface AdminUserInfo {
    username: UserId;
    displayName: string;
    role: Variant_admin_user;
    isActive: boolean;
}
export interface ReviewData {
    totalScore: number;
    questions: Array<ReviewQuestion>;
    sectionScores: Array<SectionResult>;
}
export interface UpdateQuestionInput {
    imageBlob?: ExternalBlob;
    explanation?: string;
    text: string;
    audioUrl?: string;
    questionType: QuestionType;
    sectionId?: bigint;
    correctAnswers: Array<bigint>;
    correctText: string;
    correctOrder: Array<bigint>;
    options: Array<string>;
}
export interface QuestionMastery {
    userId: UserId;
    updatedAt: Timestamp;
    isMastered: boolean;
    questionId: QuestionId;
    testId: TestId;
    correctStreak: bigint;
}
export interface SectionMasteryInfo {
    timeSpentSeconds: bigint;
    totalInSection: bigint;
    sectionName: string;
    sectionId: SectionId;
    masteredCount: bigint;
    isSectionMastered: boolean;
}
export interface AnswerSubmission {
    selectedOptions: Array<bigint>;
    orderedItems: Array<bigint>;
    textAnswer: string;
    questionId: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type TestId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Test {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
}
export type QuestionId = bigint;
export interface TestFullData {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    questions: Array<Question>;
    sections: Array<SectionData>;
}
export interface SectionData {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    testId: bigint;
}
export interface TestResult {
    completedAt: bigint;
    timeSpentSeconds: bigint;
    username: string;
    questionResults: Array<QuestionResult>;
    score: bigint;
    totalQuestions: bigint;
    sessionId: string;
    testId: bigint;
    sectionResults: Array<SectionResult>;
}
export interface QuestionResult {
    isCorrect: boolean;
    questionId: bigint;
}
export type UserId = string;
export interface DataManifest {
    testCount: bigint;
    globalUpdatedAt: string;
    sectionCount: bigint;
    checksum: string;
    questionCount: bigint;
}
export interface UpdateTestInput {
    name: string;
    description: string;
}
export interface ResetMasteryInput {
    sectionId?: SectionId;
    testId: TestId;
}
export type LoginResult = {
    __kind__: "ok";
    ok: UserSession;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "accountDeactivated";
    accountDeactivated: null;
} | {
    __kind__: "requiresTOTP";
    requiresTOTP: null;
};
export interface Section {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    testId: bigint;
}
export interface UserDetailedProgress {
    tests: Array<TestMasteryInfo>;
    username: UserId;
    lifetimeTimeSpentSeconds: bigint;
}
export type SectionId = bigint;
export interface Question {
    id: bigint;
    imageBlob?: ExternalBlob;
    explanation?: string;
    questionUpdatedAt: bigint;
    text: string;
    audioUrl?: string;
    questionType: QuestionType;
    sectionId?: bigint;
    correctAnswers: Array<bigint>;
    correctText: string;
    correctOrder: Array<bigint>;
    testId: bigint;
    options: Array<string>;
    orderIndex: bigint;
}
export interface UserProgressInfo {
    inProgressCount: bigint;
    username: UserId;
    totalQuestions: bigint;
    masteredCount: bigint;
    testId: TestId;
}
export enum QuestionType {
    textInput = "textInput",
    mcSingle = "mcSingle",
    dragOrder = "dragOrder",
    mcMulti = "mcMulti"
}
export enum Variant_admin_user {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addQuestion(username: string, testId: bigint, input: CreateQuestionInput): Promise<Question>;
    adminActivateUser(callerUsername: string, username: UserId): Promise<boolean>;
    adminDeactivateUser(callerUsername: string, username: UserId): Promise<boolean>;
    adminDeleteUser(callerUsername: string, targetUsername: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetUserDetailedProgress(callerUsername: string, username: UserId): Promise<UserDetailedProgress>;
    adminGetUserProgress(callerUsername: string, username: UserId, testId: TestId): Promise<UserProgressInfo | null>;
    adminListUsers(username: string): Promise<Array<AdminUserInfo>>;
    adminResetUserMastery(callerUsername: string, username: UserId, input: ResetMasteryInput): Promise<boolean>;
    createSection(username: string, testId: bigint, input: CreateSectionInput): Promise<Section>;
    createTest(username: string, input: CreateTestInput): Promise<Test>;
    deleteQuestion(username: string, questionId: bigint): Promise<boolean>;
    deleteSection(username: string, sectionId: bigint): Promise<boolean>;
    deleteTest(username: string, testId: bigint): Promise<boolean>;
    disable2FA(username: string, password: string, code: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    enable2FA(username: string, code: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAdminDashboardStats(callerUsername: string): Promise<AdminDashboardStats>;
    getAllTestData(): Promise<AllTestData>;
    getDataManifest(): Promise<DataManifest>;
    getMasteryForTest(username: string, testId: TestId): Promise<Array<QuestionMastery>>;
    getQuestion(questionId: bigint): Promise<Question | null>;
    getSection(sectionId: bigint): Promise<Section | null>;
    getTest(testId: bigint): Promise<Test | null>;
    getTestProgress(username: string, testId: bigint, sessionId: string): Promise<TestProgress | null>;
    getTestResult(username: string, testId: bigint): Promise<TestResult | null>;
    getTestResultBySession(username: string, testId: bigint, sessionId: string): Promise<TestResult | null>;
    getTestReview(username: string, testId: bigint, sessionId: string): Promise<ReviewData | null>;
    getTwoFAStatus(username: string): Promise<boolean>;
    getUserProgress(username: UserId): Promise<UserDetailedProgress>;
    getUserRole(username: string): Promise<UserRole | null>;
    listActiveTestSessions(username: string): Promise<Array<SessionInfo>>;
    listMyTestResults(username: string): Promise<Array<TestResult>>;
    listQuestionsForTest(testId: bigint): Promise<Array<Question>>;
    listSectionsForTest(testId: bigint): Promise<Array<Section>>;
    listTests(): Promise<Array<Test>>;
    login(username: string, password: string): Promise<LoginResult>;
    register(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetMyMastery(username: string, input: ResetMasteryInput): Promise<void>;
    saveTestProgress(username: string, testId: bigint, sessionId: string, answers: Array<AnswerSubmission>): Promise<void>;
    setup2FA(username: string): Promise<{
        __kind__: "ok";
        ok: [string, string];
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitTestAnswers(username: string, testId: bigint, sessionId: string, submissions: Array<AnswerSubmission>, timeSpentSeconds: bigint): Promise<TestResult>;
    updatePassword(username: string, currentPassword: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProfile(username: string, displayName: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateQuestion(username: string, questionId: bigint, input: UpdateQuestionInput): Promise<Question | null>;
    updateSection(username: string, sectionId: bigint, input: UpdateSectionInput): Promise<Section | null>;
    updateTest(username: string, testId: bigint, input: UpdateTestInput): Promise<Test | null>;
    verifyTOTPLogin(username: string, code: string): Promise<{
        __kind__: "ok";
        ok: UserSession;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AdminUserInfo as _AdminUserInfo, AllTestData as _AllTestData, CreateQuestionInput as _CreateQuestionInput, DataManifest as _DataManifest, ExternalBlob as _ExternalBlob, LoginResult as _LoginResult, Question as _Question, QuestionType as _QuestionType, ResetMasteryInput as _ResetMasteryInput, ReviewData as _ReviewData, ReviewQuestion as _ReviewQuestion, Section as _Section, SectionData as _SectionData, SectionId as _SectionId, SectionResult as _SectionResult, Test as _Test, TestFullData as _TestFullData, TestId as _TestId, TestProgress as _TestProgress, TestResult as _TestResult, UpdateQuestionInput as _UpdateQuestionInput, UserId as _UserId, UserProgressInfo as _UserProgressInfo, UserRole as _UserRole, UserSession as _UserSession, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addQuestion(arg0: string, arg1: bigint, arg2: CreateQuestionInput): Promise<Question> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, await to_candid_CreateQuestionInput_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Question_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, await to_candid_CreateQuestionInput_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Question_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminActivateUser(arg0: string, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminActivateUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminActivateUser(arg0, arg1);
            return result;
        }
    }
    async adminDeactivateUser(arg0: string, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeactivateUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeactivateUser(arg0, arg1);
            return result;
        }
    }
    async adminDeleteUser(arg0: string, arg1: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0, arg1);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0, arg1);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserDetailedProgress(arg0: string, arg1: UserId): Promise<UserDetailedProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserDetailedProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserDetailedProgress(arg0, arg1);
            return result;
        }
    }
    async adminGetUserProgress(arg0: string, arg1: UserId, arg2: TestId): Promise<UserProgressInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserProgress(arg0, arg1, arg2);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserProgress(arg0, arg1, arg2);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(arg0: string): Promise<Array<AdminUserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminResetUserMastery(arg0: string, arg1: UserId, arg2: ResetMasteryInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetUserMastery(arg0, arg1, to_candid_ResetMasteryInput_n26(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetUserMastery(arg0, arg1, to_candid_ResetMasteryInput_n26(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createSection(arg0: string, arg1: bigint, arg2: CreateSectionInput): Promise<Section> {
        if (this.processError) {
            try {
                const result = await this.actor.createSection(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSection(arg0, arg1, arg2);
            return result;
        }
    }
    async createTest(arg0: string, arg1: CreateTestInput): Promise<Test> {
        if (this.processError) {
            try {
                const result = await this.actor.createTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTest(arg0, arg1);
            return result;
        }
    }
    async deleteQuestion(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0, arg1);
            return result;
        }
    }
    async deleteSection(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSection(arg0, arg1);
            return result;
        }
    }
    async deleteTest(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0, arg1);
            return result;
        }
    }
    async disable2FA(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.disable2FA(arg0, arg1, arg2);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disable2FA(arg0, arg1, arg2);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async enable2FA(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.enable2FA(arg0, arg1);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enable2FA(arg0, arg1);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminDashboardStats(arg0: string): Promise<AdminDashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats(arg0);
            return result;
        }
    }
    async getAllTestData(): Promise<AllTestData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestData();
                return from_candid_AllTestData_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestData();
            return from_candid_AllTestData_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataManifest(): Promise<DataManifest> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataManifest();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataManifest();
            return result;
        }
    }
    async getMasteryForTest(arg0: string, arg1: TestId): Promise<Array<QuestionMastery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasteryForTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasteryForTest(arg0, arg1);
            return result;
        }
    }
    async getQuestion(arg0: bigint): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestion(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestion(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSection(arg0: bigint): Promise<Section | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSection(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSection(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTest(arg0: bigint): Promise<Test | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTest(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTest(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestProgress(arg0: string, arg1: bigint, arg2: string): Promise<TestProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestProgress(arg0, arg1, arg2);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestProgress(arg0, arg1, arg2);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestResult(arg0: string, arg1: bigint): Promise<TestResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResult(arg0, arg1);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResult(arg0, arg1);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestResultBySession(arg0: string, arg1: bigint, arg2: string): Promise<TestResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResultBySession(arg0, arg1, arg2);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResultBySession(arg0, arg1, arg2);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestReview(arg0: string, arg1: bigint, arg2: string): Promise<ReviewData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestReview(arg0, arg1, arg2);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestReview(arg0, arg1, arg2);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTwoFAStatus(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getTwoFAStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTwoFAStatus(arg0);
            return result;
        }
    }
    async getUserProgress(arg0: UserId): Promise<UserDetailedProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress(arg0);
            return result;
        }
    }
    async getUserRole(arg0: string): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveTestSessions(arg0: string): Promise<Array<SessionInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveTestSessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveTestSessions(arg0);
            return result;
        }
    }
    async listMyTestResults(arg0: string): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyTestResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyTestResults(arg0);
            return result;
        }
    }
    async listQuestionsForTest(arg0: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestionsForTest(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestionsForTest(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSectionsForTest(arg0: bigint): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSectionsForTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSectionsForTest(arg0);
            return result;
        }
    }
    async listTests(): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTests();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetMyMastery(arg0: string, arg1: ResetMasteryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetMyMastery(arg0, to_candid_ResetMasteryInput_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetMyMastery(arg0, to_candid_ResetMasteryInput_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveTestProgress(arg0: string, arg1: bigint, arg2: string, arg3: Array<AnswerSubmission>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTestProgress(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTestProgress(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setup2FA(arg0: string): Promise<{
        __kind__: "ok";
        ok: [string, string];
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setup2FA(arg0);
                return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setup2FA(arg0);
            return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTestAnswers(arg0: string, arg1: bigint, arg2: string, arg3: Array<AnswerSubmission>, arg4: bigint): Promise<TestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestAnswers(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestAnswers(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePassword(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePassword(arg0, arg1, arg2);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePassword(arg0, arg1, arg2);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuestion(arg0: string, arg1: bigint, arg2: UpdateQuestionInput): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, arg1, await to_candid_UpdateQuestionInput_n53(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, arg1, await to_candid_UpdateQuestionInput_n53(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSection(arg0: string, arg1: bigint, arg2: UpdateSectionInput): Promise<Section | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSection(arg0, arg1, arg2);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSection(arg0, arg1, arg2);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTest(arg0: string, arg1: bigint, arg2: UpdateTestInput): Promise<Test | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(arg0, arg1, arg2);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(arg0, arg1, arg2);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyTOTPLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: UserSession;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTOTPLogin(arg0, arg1);
                return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTOTPLogin(arg0, arg1);
            return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminUserInfo_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserInfo): AdminUserInfo {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_AllTestData_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AllTestData): Promise<AllTestData> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LoginResult_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Question_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Promise<Question> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewData_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewData): ReviewData {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewQuestion_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewQuestion): ReviewQuestion {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_TestFullData_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestFullData): Promise<TestFullData> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserSession_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSession): UserSession {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProgressInfo]): UserProgressInfo | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Question]): Promise<Question | null> {
    return value.length === 0 ? null : await from_candid_Question_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Section]): Section | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Test]): Test | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestProgress]): TestProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestResult]): TestResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReviewData]): ReviewData | null {
    return value.length === 0 ? null : from_candid_ReviewData_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    imageBlob: [] | [_ExternalBlob];
    explanation: [] | [string];
    questionUpdatedAt: bigint;
    text: string;
    audioUrl: [] | [string];
    questionType: _QuestionType;
    sectionId: [] | [bigint];
    correctAnswers: Array<bigint>;
    correctText: string;
    correctOrder: Array<bigint>;
    testId: bigint;
    options: Array<string>;
    orderIndex: bigint;
}): Promise<{
    id: bigint;
    imageBlob?: ExternalBlob;
    explanation?: string;
    questionUpdatedAt: bigint;
    text: string;
    audioUrl?: string;
    questionType: QuestionType;
    sectionId?: bigint;
    correctAnswers: Array<bigint>;
    correctText: string;
    correctOrder: Array<bigint>;
    testId: bigint;
    options: Array<string>;
    orderIndex: bigint;
}> {
    return {
        id: value.id,
        imageBlob: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.imageBlob)),
        explanation: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.explanation)),
        questionUpdatedAt: value.questionUpdatedAt,
        text: value.text,
        audioUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.audioUrl)),
        questionType: from_candid_QuestionType_n18(_uploadFile, _downloadFile, value.questionType),
        sectionId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.sectionId)),
        correctAnswers: value.correctAnswers,
        correctText: value.correctText,
        correctOrder: value.correctOrder,
        testId: value.testId,
        options: value.options,
        orderIndex: value.orderIndex
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: _UserId;
    displayName: string;
    role: {
        admin: null;
    } | {
        user: null;
    };
    isActive: boolean;
}): {
    username: UserId;
    displayName: string;
    role: Variant_admin_user;
    isActive: boolean;
} {
    return {
        username: value.username,
        displayName: value.displayName,
        role: from_candid_variant_n25(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tests: Array<_TestFullData>;
    manifest: _DataManifest;
}): Promise<{
    tests: Array<TestFullData>;
    manifest: DataManifest;
}> {
    return {
        tests: await from_candid_vec_n30(_uploadFile, _downloadFile, value.tests),
        manifest: value.manifest
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    questions: Array<_Question>;
    sections: Array<_SectionData>;
}): Promise<{
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    questions: Array<Question>;
    sections: Array<SectionData>;
}> {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        questions: await from_candid_vec_n33(_uploadFile, _downloadFile, value.questions),
        sections: value.sections
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalScore: number;
    questions: Array<_ReviewQuestion>;
    sectionScores: Array<_SectionResult>;
}): {
    totalScore: number;
    questions: Array<ReviewQuestion>;
    sectionScores: Array<SectionResult>;
} {
    return {
        totalScore: value.totalScore,
        questions: from_candid_vec_n42(_uploadFile, _downloadFile, value.questions),
        sectionScores: value.sectionScores
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: {
        id: bigint;
        explanation: [] | [string];
        text: string;
        questionType: {
            textInput: null;
        } | {
            mcSingle: null;
        } | {
            dragOrder: null;
        } | {
            mcMulti: null;
        };
        options: Array<string>;
    };
    correctAnswer: string;
    userAnswer: string;
    isCorrect: boolean;
}): {
    question: {
        id: bigint;
        explanation?: string;
        text: string;
        questionType: QuestionType;
        options: Array<string>;
    };
    correctAnswer: string;
    userAnswer: string;
    isCorrect: boolean;
} {
    return {
        question: from_candid_record_n45(_uploadFile, _downloadFile, value.question),
        correctAnswer: value.correctAnswer,
        userAnswer: value.userAnswer,
        isCorrect: value.isCorrect
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    explanation: [] | [string];
    text: string;
    questionType: {
        textInput: null;
    } | {
        mcSingle: null;
    } | {
        dragOrder: null;
    } | {
        mcMulti: null;
    };
    options: Array<string>;
}): {
    id: bigint;
    explanation?: string;
    text: string;
    questionType: QuestionType;
    options: Array<string>;
} {
    return {
        id: value.id,
        explanation: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.explanation)),
        text: value.text,
        questionType: from_candid_variant_n19(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: [] | [string];
    role: _UserRole;
}): {
    username: string;
    displayName?: string;
    role: UserRole;
} {
    return {
        username: value.username,
        displayName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.displayName)),
        role: from_candid_UserRole_n47(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    textInput: null;
} | {
    mcSingle: null;
} | {
    dragOrder: null;
} | {
    mcMulti: null;
}): QuestionType {
    return "textInput" in value ? QuestionType.textInput : "mcSingle" in value ? QuestionType.mcSingle : "dragOrder" in value ? QuestionType.dragOrder : "mcMulti" in value ? QuestionType.mcMulti : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Variant_admin_user {
    return "admin" in value ? Variant_admin_user.admin : "user" in value ? Variant_admin_user.user : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserSession;
} | {
    err: string;
} | {
    accountDeactivated: null;
} | {
    requiresTOTP: null;
}): {
    __kind__: "ok";
    ok: UserSession;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "accountDeactivated";
    accountDeactivated: null;
} | {
    __kind__: "requiresTOTP";
    requiresTOTP: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserSession_n50(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "accountDeactivated" in value ? {
        __kind__: "accountDeactivated",
        accountDeactivated: value.accountDeactivated
    } : "requiresTOTP" in value ? {
        __kind__: "requiresTOTP",
        requiresTOTP: value.requiresTOTP
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [string, string];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: [string, string];
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserSession;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserSession;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserSession_n50(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserInfo>): Array<AdminUserInfo> {
    return value.map((x)=>from_candid_AdminUserInfo_n23(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestFullData>): Promise<Array<TestFullData>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TestFullData_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Promise<Array<Question>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Question_n13(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReviewQuestion>): Array<ReviewQuestion> {
    return value.map((x)=>from_candid_ReviewQuestion_n43(_uploadFile, _downloadFile, x));
}
async function to_candid_CreateQuestionInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateQuestionInput): Promise<_CreateQuestionInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_QuestionType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ResetMasteryInput_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResetMasteryInput): _ResetMasteryInput {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateQuestionInput_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateQuestionInput): Promise<_UpdateQuestionInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sectionId?: SectionId;
    testId: TestId;
}): {
    sectionId: [] | [_SectionId];
    testId: _TestId;
} {
    return {
        sectionId: value.sectionId ? candid_some(value.sectionId) : candid_none(),
        testId: value.testId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageBlob?: ExternalBlob;
    explanation?: string;
    text: string;
    audioUrl?: string;
    questionType: QuestionType;
    sectionId?: bigint;
    correctAnswers: Array<bigint>;
    correctText: string;
    correctOrder: Array<bigint>;
    options: Array<string>;
}): Promise<{
    imageBlob: [] | [_ExternalBlob];
    explanation: [] | [string];
    text: string;
    audioUrl: [] | [string];
    questionType: _QuestionType;
    sectionId: [] | [bigint];
    correctAnswers: Array<bigint>;
    correctText: string;
    correctOrder: Array<bigint>;
    options: Array<string>;
}> {
    return {
        imageBlob: value.imageBlob ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.imageBlob)) : candid_none(),
        explanation: value.explanation ? candid_some(value.explanation) : candid_none(),
        text: value.text,
        audioUrl: value.audioUrl ? candid_some(value.audioUrl) : candid_none(),
        questionType: to_candid_QuestionType_n11(_uploadFile, _downloadFile, value.questionType),
        sectionId: value.sectionId ? candid_some(value.sectionId) : candid_none(),
        correctAnswers: value.correctAnswers,
        correctText: value.correctText,
        correctOrder: value.correctOrder,
        options: value.options
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    textInput: null;
} | {
    mcSingle: null;
} | {
    dragOrder: null;
} | {
    mcMulti: null;
} {
    return value == QuestionType.textInput ? {
        textInput: null
    } : value == QuestionType.mcSingle ? {
        mcSingle: null
    } : value == QuestionType.dragOrder ? {
        dragOrder: null
    } : value == QuestionType.mcMulti ? {
        mcMulti: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
